include:
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml

image: golang:1.19

.task:
  stage: test
  only:
    - merge_request
  before_script:
    - go install github.com/go-task/task/v3/cmd/task@latest
    - task install_tools
  #   - mkdir -p .go
  # variables:
  #   GOPATH: $CI_PROJECT_DIR/.go
  # cache:
  #   paths:
  #     - .go/pkg/mod/

stages:
  - test
  - deploy

format:
  extends:
    - .task
  script:
    - task format

lint:
  image: registry.gitlab.com/gitlab-org/gitlab-build-images:golangci-lint-alpine
  extends:
    - .task
  script:
    - task lint -- --out-format code-climate:codequality.json,colored-line-number
  artifacts:
    when: always
    expire_in: 1 week
    reports:
      codequality: codequality.json

test:coverage:
  only:
    - main
    - merge_request
  extends:
    - .task
  script:
    - task coverage
  allow_failure: true
  coverage: '/total:.*\d+.\d+%/'
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: report.xml

deploy:
  stage: deploy
  only:
    - main
  image: docker
  services:
    - docker:dind
  before_script:
    - apk add curl
    - curl -L https://fly.io/install.sh | sh
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker build --cache-from ${CI_REGISTRY_IMAGE} -t ${CI_REGISTRY_IMAGE}:latest -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} -t ${CI_REGISTRY_IMAGE}:deploy .
    - docker push ${CI_REGISTRY_IMAGE} --all-tags
    - /root/.fly/bin/flyctl deploy
