image: golang:1.19

stages:
  - publish
  - deploy

publish:docker:
  stage: publish
  only:
    - main
  image: docker
  services:
    - docker:dind
  before_script: []
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker build --cache-from ${CI_REGISTRY_IMAGE} -t ${CI_REGISTRY_IMAGE}:latest -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG} .
    - docker push ${CI_REGISTRY_IMAGE} --all-tags

deploy:
  stage: deploy
  image: flyio/flyctl
  only:
    - main
  before_script: []
  script:
    - flyctl deploy
