include:
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Code-Quality.gitlab-ci.yml

image: golang:1.20

.task:
  stage: test
  only:
    - merge_request
  before_script:
    - go install github.com/go-task/task/v3/cmd/task@latest
    - task install

stages:
  - test
  - deploy
  - notify
  - release

format:
  extends:
    - .task
  script:
    - task format

lint:
  image: golangci/golangci-lint:v1.52.2-alpine
  extends:
    - .task
  script:
    - task lint

coverage:
  extends:
    - .task
  only:
    - main
    - merge_request
  script:
    - task coverage
  coverage: /^coverage:\s(\d+(?:\.\d+)?%)/
  artifacts:
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

deploy:preview:
  stage: deploy
  only:
    - merge_request
  needs: []
  image: docker
  services:
    - docker:dind
  before_script:
    - apk add curl
    - curl -L https://fly.io/install.sh | sh
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker build --cache-from ${CI_REGISTRY_IMAGE} -t ${CI_REGISTRY_IMAGE}:deploy .
    - /root/.fly/bin/flyctl deploy --config ./fly.preview.toml

deploy:production:
  stage: deploy
  only:
    - main
  image: docker
  services:
    - docker:dind
  before_script:
    - apk add curl
    - curl -L https://fly.io/install.sh | sh
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker build --cache-from ${CI_REGISTRY_IMAGE} -t ${CI_REGISTRY_IMAGE}:latest -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} -t ${CI_REGISTRY_IMAGE}:deploy .
    - docker push ${CI_REGISTRY_IMAGE} --all-tags
    - /root/.fly/bin/flyctl deploy --config ./fly.production.toml

notify:success:
  stage: notify
  only:
    - main
  before_script: []
  script:
    - wget https://raw.githubusercontent.com/hmajid2301/gitlab-ci-discord-webhook/master/send.sh
    - chmod +x send.sh
    - ./send.sh success "🚀 Successfully deployed to fly.io"
  when: on_success

notify:failure:
  stage: notify
  only:
    - main
  before_script: []
  script:
    - wget https://raw.githubusercontent.com/hmajid2301/gitlab-ci-discord-webhook/master/send.sh
    - chmod +x send.sh
    - ./send.sh failure "❌ Failed to deploy to fly.io"
  when: on_failure

release:sentry:
  stage: release
  only:
    - main
  image:
    name: getsentry/sentry-cli
    entrypoint: [""]
  variables:
    SENTRY_ORG: bookmarkey
    SENTRY_PROJECT: api
  dependencies:
    - "deploy:preview"
  script:
    - sentry-cli releases new "$CI_COMMIT_SHA"
    - sentry-cli releases set-commits "$CI_COMMIT_SHA" --auto
    - sentry-cli releases finalize "$CI_COMMIT_SHA"
    - sentry-cli releases deploys "$CI_COMMIT_SHA" new -e production
