run:
  timeout: 5m
  modules-download-mode: readonly
  skip-dirs:
    - migrations

linters:
  enable:
    - revive
    - govet
    - errcheck
    - goimports
    - staticcheck
    - unconvert

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
