services:
  app:
    image: registry.gitlab.com/bookmarkey/api:deploy
    build:
      dockerfile: Dockerfile
      context: .
      cache_from:
        - registry.gitlab.com/bookmarkey/api:latest
    volumes:
      - .:/build
    ports:
      - 8080:8080
