version: "3"

tasks:
  build:
    desc: Builds the app into a binary.
    cmds:
      - go build cmd/server/bookmarkey/main.go

  start:
    desc: Starts the app locally.
    cmds:
      - go run cmd/server/bookmarkey/main.go serve --http=localhost:8080

  start:docker:
    desc: Starts the app in docker.
    cmds:
      - docker compose up --build -d

  lint:
    desc: Runs the linter.
    cmds:
      # - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.52.2
      - golangci-lint run {{.CLI_ARGS}}

  format:
    desc: Runs the formatter.
    cmds:
      - goimports -local gitlab.com/bookmarkey/api -w .

  install:tools:
    desc: Install all the tool (binaries), such as junit.
    internal: true
    cmds:
      - cat tools.go | grep _ | awk -F'"' '{print $2}' | xargs -tI % go install %

  install:precommit:
    desc: Installs git pre-commit hooks.
    internal: true
    cmds:
      - pre-commit install

  install:
    desc: Install all deps for this project
    deps: [install:tools]
    cmds:
      - go mod download

  start:test:
    desc: Starts the app using the test data.
    cmds:
      - go run cmd/server/bookmarkey/main.go serve --dir tests/pb_data  --http=localhost:8080

  tests:unit:
    desc: Runs all the unit tests.
    cmds:
      - go test ./...

  tests:integration:
    desc: Runs all the integration tests tests.
    cmds:
      - go test -tags=integration -v ./internal/...

  coverage:
    desc: Run the integration tests and gets the code coverage
    cmds:
      - go test -coverprofile=coverage.txt -tags=integration -v ./internal/... | tee output.txt
      - cat output.txt | go-junit-report -set-exit-code > report.xml
      - gocover-cobertura < coverage.txt > coverage.xml
