version: "3"

tasks:
  build:
    cmds:
      - go build -i -v cmd/server/bookmarkey/main.go

  start:
    cmds:
      - go run cmd/server/bookmarkey/main.go serve --http=localhost:8080

  start:docker:
    cmds:
      - docker compose up --build -d

  lint:
    cmds:
      - golangci-lint run {{.CLI_ARGS}}

  format:
    cmds:
      - go install golang.org/x/tools/cmd/goimports
      - goimports -local gitlab.com/bookmarkey/api -w .

  install:precommit:
    cmds:
      - pre-commit install

  start:test:
    cmds:
      - go run cmd/server/bookmarkey/main.go serve --dir tests/pb_data  --http=localhost:8080

  unit:tests:
    cmds:
      - go test ./...

  integration:tests:
    cmds:
      - go test -tags=integration -v ./internal/...

  coverage:
    cmds:
      - go test -coverprofile=coverage.txt -tags=integration -v ./internal/... | go-junit-report -set-exit-code > report.xml
      - gocover-cobertura < coverage.txt > coverage.xml
