version: "3"

tasks:
  build:
    cmds:
      - go build -i -v cmd/server/bookmarkey/main.go

  start:
    cmds:
      - go run cmd/server/bookmarkey/main.go serve --http=localhost:8080

  start_docker:
    cmds:
      - docker compose up --build -d

  start_test:
    cmds:
      - go run cmd/server/bookmarkey/main.go serve --dir tests/pb_data

  unit_tests:
    cmds:
      - go test ./...

  integration_tests:
    cmds:
      - go test -tags=integration -v ./internal/...

  coverage:
    cmds:
      - go test -coverprofile=coverage.txt -tags=integration -v ./internal/... | go-junit-report -set-exit-code > report.xml
      - gocover-cobertura < coverage.txt > coverage.xml

  lint:
    cmds:
      - golangci-lint run {{.CLI_ARGS}}

  format:
    cmds:
      - goimports -local gitlab.com/bookmarkey/api -w .

  install_tools:
    cmds:
      - go mod download
      - cat tools.go | grep _ | cut -d '"' -f2 | xargs -tI % go install %

  install_pre_commit:
    cmds:
      - pre-commit install
